---
- name: Update GRUB configuration
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  register: grub_update
  changed_when: grub_update.rc != 0

- name: Rebuild initramfs
  command: dracut -f -v
  register: dracut_rebuild
  changed_when: dracut_rebuild.rc != 0

- name: Verify fstab entries
  command: cat /etc/fstab
  register: fstab_content
  changed_when: false

- name: Display fstab content
  debug:
    var: fstab_content.stdout_lines

- name: Check boot partition
  command: mount | grep /boot
  register: boot_mount
  changed_when: false

- name: Display boot partition info
  debug:
    var: boot_mount.stdout_lines

- name: Check LVM modules in initramfs
  shell: lsinitrd /boot/initramfs-$(uname -r).img | grep lvm
  register: lvm_in_initramfs
  changed_when: false

- name: Display LVM modules in initramfs
  debug:
    var: lvm_in_initramfs.stdout_lines

- name: Verify GRUB default target
  command: grep GRUB_DEFAULT /etc/default/grub
  register: grub_default
  changed_when: false

- name: Display GRUB default target
  debug:
    var: grub_default.stdout_lines

- name: Check if /boot is on LVM
  command: lvs --noheadings -o lv_path | grep /boot
  register: boot_on_lvm
  changed_when: false
  failed_when: false

- name: Display if /boot is on LVM
  debug:
    msg: "/boot is {{ 'on' if boot_on_lvm.rc == 0 else 'not on' }} LVM"