---
- name: Configure RHEL 9 with LVM and Packages
  hosts: all
  become: true
  vars:
    lvm_physical_volume: /dev/nvme1n1  # This should match the device name we added
    lvm_volume_group: rootvg
    lvm_logical_volumes:
      - name: root
        size: 10G
      - name: var
        size: 5G
  roles:
    - role: debug-instance-info
    - role: rhel-manager
    - role: configure_lvm
    - role: snapshot_create
      snapshot_create_set_name: rhel9snapshot
      snapshot_create_snapshot_autoextend_threshold: 70
      snapshot_create_snapshot_autoextend_percent: 20
      snapshot_create_boot_backup: true
      snapshot_create_volumes: 
        - vg: "{{ lvm_volume_group }}"
          lv: root
          size: 2G
        - vg: "{{ lvm_volume_group }}"
          lv: var
          size: 2G
    - role: boot_check

