---
- name: Verify mounts
  command: mount
  register: mount_output

- name: Display mounts
  debug:
    var: mount_output.stdout_lines

- name: Final reboot
  reboot:
    msg: "Rebooting to finalize system configuration"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  become: true